# Joke Database
JOKES = {
    "general": [
        "Why don't scientists trust atoms? Because they make up everything!",
        "What do you call a fake noodle? An impasta!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "What do you call a fish with no eyes? A fsh!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a bear with no teeth? A gummy bear!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What do you call a sleeping dinosaur? A dino-snore!",
        "Why don't eggs tell jokes? They'd crack each other up!",
        "What do you call a cow with no legs? Ground beef!",
        "Why did the math book look so sad? Because it had too many problems!",
        "What do you call a snowman with a six-pack? An abdominal snowman!",
        "Why did the gym close down? It just didn't work out!",
        "What do you call a dog with a magic wand? A labracadabrador!",
        "Why did the bicycle fall over? Because it was two-tired!",
        "What do you call an alligator in a vest? An investigator!",
        "Why did the golfer wear two pairs of pants? In case he got a hole in one!",
        "What do you call a pig that does karate? A pork chop!",
        "Why did the baker go to therapy? He had too many kneads!",
        "What do you call a magic dog? A labracadabrador!"
    ],
    
    "dad": [
        "What's brown and sticky? A stick.",
        "What do you call a fake noodle? An impasta.",
        "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
        "Why don't crabs share their food? Because they're shellfish.",
        "What do you call a fly without wings? A walk.",
        "Why did the picture go to jail? Because it was framed.",
        "I'm reading a book about anti-gravity. It's impossible to put down!",
        "What's orange and sounds like a parrot? A carrot.",
        "Why can't you trust stairs? They're always up to something.",
        "What do you call a sleeping bull? A bulldozer.",
        "Why did the coffee file a police report? It got mugged.",
        "I'm afraid of elevators. I'm taking steps to avoid them.",
        "What do you call a bear in the rain? A drizzly bear.",
        "Why did the scarecrow win an award? He was outstanding in his field.",
        "What do you call a fat psychic? A four-chin teller.",
        "Why did the boy throw the clock out the window? He wanted to see time fly.",
        "What do you call a priest with a cold? A sermon with a sneeze.",
        "Why don't scientists trust atoms? Because they make up everything.",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "What do you call an alligator detective? An investi-gator."
    ],
    
    "pun": [
        "I used to be a baker, but I couldn't make enough dough.",
        "I'm reading a book about teleportation. It's bound to take me places.",
        "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "I used to play piano by ear, but now I use my hands.",
        "I'm on a seafood diet. I see food and I eat it.",
        "I tried to catch fog yesterday. Mist.",
        "I'd tell you a pizza joke, but it's a little cheesy.",
        "I was going to tell a time-traveling joke, but you didn't like it.",
        "I used to work in a shoe-recycling shop. It was sole-destroying.",
        "I'm so good at sleeping, I can do it with my eyes closed!",
        "I told my girlfriend she should embrace her mistakes. She gave me a hug.",
        "I used to have a fear of hurdles, but I got over it.",
        "I was going to tell a joke about sodium, but Na.",
        "I'm against picketing, but I don't know how to show it.",
        "I was going to be a doctor, but I didn't have the patients.",
        "I used to be a banker, but I lost interest.",
        "I told my friend 10 jokes about elevators. They all worked.",
        "I tried to be a chef, but I couldn't take the heat.",
        "I'm not great at math, but I have my moments."
    ],
    
    "programming": [
        "Why do programmers prefer dark mode? Because light attracts bugs.",
        "What's a programmer's favorite hangout? The Foo Bar.",
        "Why did the programmer quit his job? Because he didn't get arrays.",
        "What do you call a programmer from Finland? Nerdic.",
        "Why do programmers hate nature? It has too many bugs.",
        "What's a software developer's favorite game? Git push.",
        "Why did the programmer go broke? Because he used up all his cache.",
        "What's a programmer's favorite breakfast? Java.",
        "Why did the developer go to the beach? To test the waters.",
        "What do you call a programmer's kid? A chip off the old block.",
        "Why do programmers always confuse Halloween and Christmas? Because Oct 31 equals Dec 25.",
        "What's a computer's favorite beat? An algorithm.",
        "Why did the script break up with the server? Too many bad requests.",
        "What do you call a developer who doesn't comment their code? A maverick.",
        "Why did the API go to therapy? It had too many endpoints.",
        "What's a coder's favorite drink? Byte.",
        "Why did the developer cross the road? To get to the other side of the firewall.",
        "What do you call a bug that can't be fixed? A feature.",
        "Why do programmers prefer Linux? Because windows are for looking out of.",
        "What's a programmer's favorite music genre? Hip-hop with a good loop."
    ],
    
    "animals": [
        "Why don't cats play poker in the jungle? Too many cheetahs!",
        "What do you call a sleeping dinosaur? A dino-snore.",
        "Why did the elephant paint his toenails red? So he could hide in a cherry tree.",
        "What do you call a cow with a twitch? Beef jerky.",
        "Why don't seagulls fly over the bay? Because then they'd be bagels.",
        "What do you call a pig that knows karate? A pork chop.",
        "Why did the frog take the bus to work? His car was toad.",
        "What do you call a dog with a magic wand? A labracadabrador.",
        "Why don't sharks like to eat clowns? They taste funny.",
        "What do you call a bear with no teeth? A gummy bear.",
        "Why did the chicken cross the playground? To get to the other slide.",
        "What do you call a lazy kangaroo? A pouch potato.",
        "Why don't owls go on dates? They don't give a hoot.",
        "What do you call a cat that can dance? A tap-dancing tabby.",
        "Why did the horse go to the doctor? He was feeling a little hoarse.",
        "What do you call a fish with no eyes? A fsh.",
        "Why did the snake get a ticket? For speed hissing.",
        "What do you call a sheep with no legs? A cloud.",
        "Why don't gorillas like to eat bananas? They're too apeeling.",
        "What do you call a dinosaur with an extensive vocabulary? A thesaurus."
    ]
}

# Trivia Questions
TRIVIA = [
    "What is the chemical symbol for water?",
    "How many planets are in our solar system?",
    "What is the fastest animal on land?",
    "Who painted the Mona Lisa?",
    "What is the capital of Japan?",
    "In which year did World War II end?",
    "What is the hardest natural substance?",
    "What is the largest ocean on Earth?",
    "How many bones are in the human body?",
    "What is the longest river in the world?",
    "What is the currency of the United Kingdom?",
    "Who wrote the play 'Romeo and Juliet'?",
    "What is the tallest animal?",
    "How many continents are there?",
    "What gas do plants absorb from the atmosphere?",
    "What is the smallest country in the world?",
    "What year did the Titanic sink?",
    "Who developed the theory of relativity?",
    "What is the chemical formula for table salt?",
    "What is the rarest blood type?"
]

# Fun Facts
FUN_FACTS = [
    "Octopuses have three hearts.",
    "Honey never spoils. Archaeologists found 3000-year-old honey in ancient Egyptian tombs.",
    "A group of flamingos is called a 'flamboyance'.",
    "Bananas are berries, but strawberries aren't.",
    "The average person walks the equivalent of three times around the world in a lifetime.",
    "Cows have best friends and get stressed when separated.",
    "The human nose can remember 50,000 different scents.",
    "A single cloud can weigh more than a million pounds.",
    "The shortest war in history was between Britain and Zanzibar in 1896 - it lasted 38 minutes.",
    "There are more stars in the universe than grains of sand on all beaches on Earth.",
    "The heart of a shrimp is located in its head.",
    "It's impossible to sneeze with your eyes open.",
    "The total weight of all the ants on Earth is about equal to the total weight of all humans.",
    "A jiffy is an actual unit of time: 1/100th of a second.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "An octopus has three hearts and blue blood.",
    "The sound you hear when you crack your knuckles is gas bubbles bursting.",
    "Every day, the Earth gains about 60 tons of mass from space dust.",
    "The lifespan of a taste bud is about 10 days.",
    "The Atlantic Ocean is saltier than the Pacific Ocean."
]
